name: pi3
version: 16.04-0.5
summary: Raspberry Pi 3 support package
description: |
 Support files for booting Raspberry Pi 3 for classic Ubuntu
type: gadget
architectures:
  - armhf
confinement: strict
grade: stable
parts:
  gadget:
    source: .
    plugin: make
    prime:
      - boot-assets/*
      - uboot*